// Code generated by the Encore v1.57.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-bright-steps-centre-success-uwhi.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the bright-steps-centre-success-uwhi Encore application.
 */
export default class Client {
    public readonly foundation: foundation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.foundation = new foundation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: authentication.AuthenticationParams | AuthDataGenerator
}

/**
 * Centre Success begins as one cohesive Encore service. Logical foundation
 * modules remain internal until an evidence-backed extraction is approved.
 */
export namespace foundation {
    export interface FoundationHealthResponse {
        status: "operational"
        milestone: "1"
        backend: "connected"
        database: "available"
        checkedAt: string
    }

    export interface FoundationMeResponse {
        provisioningStatus: "provisioned" | "not_provisioned"
        principal?: {
            id: string
            displayName: string
        }
        activeOrganisation?: {
            id: string
            name: string
        }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptInvitation = this.acceptInvitation.bind(this)
            this.acknowledgeQuarterlyAudit = this.acknowledgeQuarterlyAudit.bind(this)
            this.addPersonAssignment = this.addPersonAssignment.bind(this)
            this.approveInvitation = this.approveInvitation.bind(this)
            this.cancelInvitationEndpoint = this.cancelInvitationEndpoint.bind(this)
            this.completeEvidenceUpload = this.completeEvidenceUpload.bind(this)
            this.createCentreBudgetActual = this.createCentreBudgetActual.bind(this)
            this.createInvitation = this.createInvitation.bind(this)
            this.finaliseQuarterlyAudit = this.finaliseQuarterlyAudit.bind(this)
            this.getAuditPreparation = this.getAuditPreparation.bind(this)
            this.getAuthorisedNavigationEndpoint = this.getAuthorisedNavigationEndpoint.bind(this)
            this.getCentreBudgetMonth = this.getCentreBudgetMonth.bind(this)
            this.getCentreQualityDetail = this.getCentreQualityDetail.bind(this)
            this.getCentreQualityWorkspace = this.getCentreQualityWorkspace.bind(this)
            this.getComplianceOversight = this.getComplianceOversight.bind(this)
            this.getCorrectiveAction = this.getCorrectiveAction.bind(this)
            this.getDailySuccess = this.getDailySuccess.bind(this)
            this.getEvidenceAccess = this.getEvidenceAccess.bind(this)
            this.getInvitation = this.getInvitation.bind(this)
            this.getPeopleOptions = this.getPeopleOptions.bind(this)
            this.getPerson = this.getPerson.bind(this)
            this.getPersonAccess = this.getPersonAccess.bind(this)
            this.getPersonHistory = this.getPersonHistory.bind(this)
            this.getPortfolioBudgetMonth = this.getPortfolioBudgetMonth.bind(this)
            this.getQuarterlyAudit = this.getQuarterlyAudit.bind(this)
            this.health = this.health.bind(this)
            this.listAssignedAuditCentres = this.listAssignedAuditCentres.bind(this)
            this.listCorrectiveActionVerificationQueue = this.listCorrectiveActionVerificationQueue.bind(this)
            this.listMyCorrectiveActions = this.listMyCorrectiveActions.bind(this)
            this.listPeople = this.listPeople.bind(this)
            this.markQuarterlyAuditReady = this.markQuarterlyAuditReady.bind(this)
            this.me = this.me.bind(this)
            this.reactivatePerson = this.reactivatePerson.bind(this)
            this.removePersonAssignment = this.removePersonAssignment.bind(this)
            this.replacePersonAssignmentScope = this.replacePersonAssignmentScope.bind(this)
            this.requestEvidenceUpload = this.requestEvidenceUpload.bind(this)
            this.resendInvitation = this.resendInvitation.bind(this)
            this.returnCorrectiveAction = this.returnCorrectiveAction.bind(this)
            this.revokePerson = this.revokePerson.bind(this)
            this.saveQuarterlyAuditResponse = this.saveQuarterlyAuditResponse.bind(this)
            this.sendInvitation = this.sendInvitation.bind(this)
            this.startCorrectiveAction = this.startCorrectiveAction.bind(this)
            this.startQuarterlyAudit = this.startQuarterlyAudit.bind(this)
            this.submitCorrectiveActionEvidence = this.submitCorrectiveActionEvidence.bind(this)
            this.suspendPerson = this.suspendPerson.bind(this)
            this.verifyAndCloseCorrectiveAction = this.verifyAndCloseCorrectiveAction.bind(this)
        }

        public async acceptInvitation(params: people_access.AcceptInvitationRequest): Promise<people_access.AcceptInvitationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invitations/accept`, JSON.stringify(params))
            return await resp.json() as people_access.AcceptInvitationResponse
        }

        public async acknowledgeQuarterlyAudit(auditId: string, params: quarterly_reviews.AcknowledgeAuditRequest): Promise<quarterly_reviews.AcknowledgeAuditResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quarterly-reviews/audits/${encodeURIComponent(auditId)}/acknowledge`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.AcknowledgeAuditResponse
        }

        public async addPersonAssignment(principalId: string, params: people_access.AddAssignmentRequest): Promise<people_access.PersonAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/${encodeURIComponent(principalId)}/assignments`, JSON.stringify(params))
            return await resp.json() as people_access.PersonAccessResponse
        }

        public async approveInvitation(invitationId: string, params: people_access.VersionedInvitationRequest): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/invitations/${encodeURIComponent(invitationId)}/approve`, JSON.stringify(params))
            return await resp.json() as people_access.InvitationSummary
        }

        public async cancelInvitationEndpoint(invitationId: string, params: people_access.VersionedInvitationRequest): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/invitations/${encodeURIComponent(invitationId)}/cancel`, JSON.stringify(params))
            return await resp.json() as people_access.InvitationSummary
        }

        public async completeEvidenceUpload(evidenceId: string): Promise<quarterly_reviews.CompleteEvidenceUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/evidence/${encodeURIComponent(evidenceId)}/complete`)
            return await resp.json() as quarterly_reviews.CompleteEvidenceUploadResponse
        }

        public async createCentreBudgetActual(month: string, centreId: string, params: centre_budgets.RecordCentreBudgetActualRequest): Promise<centre_budgets.RecordCentreBudgetActualResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/centre-budgets/months/${encodeURIComponent(month)}/centres/${encodeURIComponent(centreId)}/actuals`, JSON.stringify(params))

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as centre_budgets.RecordCentreBudgetActualResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async createInvitation(params: people_access.CreateInvitationRequest): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/invitations`, JSON.stringify(params))
            return await resp.json() as people_access.InvitationSummary
        }

        public async finaliseQuarterlyAudit(auditId: string, params: quarterly_reviews.AuditTransitionRequest): Promise<quarterly_reviews.FinaliseQuarterlyAuditResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quarterly-reviews/audits/${encodeURIComponent(auditId)}/finalise`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.FinaliseQuarterlyAuditResponse
        }

        public async getAuditPreparation(centreId: string): Promise<quarterly_reviews.AuditPreparationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/quarterly-reviews/centres/${encodeURIComponent(centreId)}/preparation`)
            return await resp.json() as quarterly_reviews.AuditPreparationResponse
        }

        public async getAuthorisedNavigationEndpoint(): Promise<navigation.NavigationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/navigation`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as navigation.NavigationResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getCentreBudgetMonth(month: string, centreId: string): Promise<centre_budgets.CentreBudgetMonthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/centre-budgets/months/${encodeURIComponent(month)}/centres/${encodeURIComponent(centreId)}`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as centre_budgets.CentreBudgetMonthResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getCentreQualityDetail(centreId: string): Promise<centre_quality.CentreQualityDetailResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/centre-quality/centres/${encodeURIComponent(centreId)}`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as centre_quality.CentreQualityDetailResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getCentreQualityWorkspace(params: centre_quality.CentreQualityWorkspaceRequest): Promise<centre_quality.CentreQualityWorkspaceResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                centreId: params.centreId,
                view:     params.view === undefined ? undefined : String(params.view),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/centre-quality`, undefined, {query})

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as centre_quality.CentreQualityWorkspaceResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getComplianceOversight(): Promise<quarterly_reviews.ComplianceOversightResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/compliance/quarterly-reviews`)
            return await resp.json() as quarterly_reviews.ComplianceOversightResponse
        }

        public async getCorrectiveAction(actionId: string): Promise<quarterly_reviews.CorrectiveActionDetail> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/corrective-actions/${encodeURIComponent(actionId)}`)
            return await resp.json() as quarterly_reviews.CorrectiveActionDetail
        }

        public async getDailySuccess(params: daily_success.DailySuccessRequest): Promise<daily_success.DailySuccessResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                centreId:    params.centreId,
                perspective: params.perspective === undefined ? undefined : String(params.perspective),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/daily-success`, undefined, {query})

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as daily_success.DailySuccessResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getEvidenceAccess(evidenceId: string): Promise<quarterly_reviews.GetEvidenceAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/evidence/${encodeURIComponent(evidenceId)}/access`)
            return await resp.json() as quarterly_reviews.GetEvidenceAccessResponse
        }

        public async getInvitation(invitationId: string): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people/invitations/${encodeURIComponent(invitationId)}`)
            return await resp.json() as people_access.InvitationSummary
        }

        public async getPeopleOptions(): Promise<people_access.PeopleAccessOptionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people/options`)
            return await resp.json() as people_access.PeopleAccessOptionsResponse
        }

        public async getPerson(principalId: string): Promise<people_access.PersonAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people/${encodeURIComponent(principalId)}`)
            return await resp.json() as people_access.PersonAccessResponse
        }

        public async getPersonAccess(principalId: string): Promise<people_access.PersonAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people/${encodeURIComponent(principalId)}/access`)
            return await resp.json() as people_access.PersonAccessResponse
        }

        public async getPersonHistory(principalId: string): Promise<people_access.AccessHistoryResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people/${encodeURIComponent(principalId)}/history`)
            return await resp.json() as people_access.AccessHistoryResponse
        }

        public async getPortfolioBudgetMonth(month: string): Promise<centre_budgets.PortfolioBudgetMonthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/centre-budgets/months/${encodeURIComponent(month)}/portfolio`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as centre_budgets.PortfolioBudgetMonthResponse
            rtn.cacheControl = mustBeSet("Header `cache-control`", resp.headers.get("cache-control"))
            return rtn
        }

        public async getQuarterlyAudit(auditId: string): Promise<quarterly_reviews.QuarterlyAuditView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/quarterly-reviews/audits/${encodeURIComponent(auditId)}`)
            return await resp.json() as quarterly_reviews.QuarterlyAuditView
        }

        /**
         * Public liveness/readiness proof for local development and the foundation
         * shell. It intentionally exposes no organisation, centre, or principal data.
         */
        public async health(): Promise<FoundationHealthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/foundation/health`)
            return await resp.json() as FoundationHealthResponse
        }

        public async listAssignedAuditCentres(): Promise<quarterly_reviews.ListAuditCentresResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/quarterly-reviews/centres`)
            return await resp.json() as quarterly_reviews.ListAuditCentresResponse
        }

        public async listCorrectiveActionVerificationQueue(): Promise<quarterly_reviews.ListCorrectiveActionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/corrective-actions/verification-queue`)
            return await resp.json() as quarterly_reviews.ListCorrectiveActionsResponse
        }

        public async listMyCorrectiveActions(): Promise<quarterly_reviews.ListCorrectiveActionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/corrective-actions/mine`)
            return await resp.json() as quarterly_reviews.ListCorrectiveActionsResponse
        }

        public async listPeople(): Promise<people_access.PeopleListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/people`)
            return await resp.json() as people_access.PeopleListResponse
        }

        public async markQuarterlyAuditReady(auditId: string, params: quarterly_reviews.AuditTransitionRequest): Promise<quarterly_reviews.AuditStatusTransitionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quarterly-reviews/audits/${encodeURIComponent(auditId)}/ready`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.AuditStatusTransitionResponse
        }

        /**
         * Minimal protected proof of Entra -> internal principal -> PostgreSQL
         * authorisation context. It intentionally returns no grants or Entra claims.
         */
        public async me(): Promise<FoundationMeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/foundation/me`)
            return await resp.json() as FoundationMeResponse
        }

        public async reactivatePerson(principalId: string, params: people_access.PrincipalLifecycleRequest): Promise<people_access.PrincipalLifecycleResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/${encodeURIComponent(principalId)}/reactivate`, JSON.stringify(params))
            return await resp.json() as people_access.PrincipalLifecycleResponse
        }

        public async removePersonAssignment(principalId: string, assignmentId: string, params: people_access.AssignmentMutationRequest): Promise<people_access.PersonAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/${encodeURIComponent(principalId)}/assignments/${encodeURIComponent(assignmentId)}/remove`, JSON.stringify(params))
            return await resp.json() as people_access.PersonAccessResponse
        }

        public async replacePersonAssignmentScope(principalId: string, assignmentId: string, params: people_access.AssignmentMutationRequest): Promise<people_access.PersonAccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/admin/people/${encodeURIComponent(principalId)}/assignments/${encodeURIComponent(assignmentId)}/scope`, JSON.stringify(params))
            return await resp.json() as people_access.PersonAccessResponse
        }

        public async requestEvidenceUpload(params: quarterly_reviews.RequestEvidenceUploadRequest): Promise<quarterly_reviews.RequestEvidenceUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/evidence/uploads`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.RequestEvidenceUploadResponse
        }

        public async resendInvitation(invitationId: string, params: people_access.VersionedInvitationRequest): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/invitations/${encodeURIComponent(invitationId)}/resend`, JSON.stringify(params))
            return await resp.json() as people_access.InvitationSummary
        }

        public async returnCorrectiveAction(actionId: string, params: quarterly_reviews.ReturnCorrectiveActionRequest): Promise<quarterly_reviews.ActionTransitionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/corrective-actions/${encodeURIComponent(actionId)}/return`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.ActionTransitionResponse
        }

        public async revokePerson(principalId: string, params: people_access.PrincipalLifecycleRequest): Promise<people_access.PrincipalLifecycleResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/${encodeURIComponent(principalId)}/revoke`, JSON.stringify(params))
            return await resp.json() as people_access.PrincipalLifecycleResponse
        }

        public async saveQuarterlyAuditResponse(auditId: string, itemId: string, params: quarterly_reviews.SaveAuditResponseRequest): Promise<quarterly_reviews.SaveAuditResponseResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/quarterly-reviews/audits/${encodeURIComponent(auditId)}/responses/${encodeURIComponent(itemId)}`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.SaveAuditResponseResponse
        }

        public async sendInvitation(invitationId: string, params: people_access.VersionedInvitationRequest): Promise<people_access.InvitationSummary> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/invitations/${encodeURIComponent(invitationId)}/send`, JSON.stringify(params))
            return await resp.json() as people_access.InvitationSummary
        }

        public async startCorrectiveAction(actionId: string, params: quarterly_reviews.StartCorrectiveActionRequest): Promise<quarterly_reviews.ActionTransitionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/corrective-actions/${encodeURIComponent(actionId)}/start`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.ActionTransitionResponse
        }

        public async startQuarterlyAudit(params: quarterly_reviews.StartQuarterlyAuditRequest): Promise<quarterly_reviews.StartQuarterlyAuditResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quarterly-reviews/audits`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.StartQuarterlyAuditResponse
        }

        public async submitCorrectiveActionEvidence(actionId: string, params: quarterly_reviews.SubmitCorrectiveActionRequest): Promise<quarterly_reviews.ActionTransitionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/corrective-actions/${encodeURIComponent(actionId)}/submit`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.ActionTransitionResponse
        }

        public async suspendPerson(principalId: string, params: people_access.PrincipalLifecycleRequest): Promise<people_access.PrincipalLifecycleResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/people/${encodeURIComponent(principalId)}/suspend`, JSON.stringify(params))
            return await resp.json() as people_access.PrincipalLifecycleResponse
        }

        public async verifyAndCloseCorrectiveAction(actionId: string, params: quarterly_reviews.VerifyCorrectiveActionRequest): Promise<quarterly_reviews.ActionTransitionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/corrective-actions/${encodeURIComponent(actionId)}/verify`, JSON.stringify(params))
            return await resp.json() as quarterly_reviews.ActionTransitionResponse
        }
    }
}

export namespace authentication {
    export interface AuthenticationParams {
        authorization: string
    }
}

export namespace centre_budgets {
    /**
     * An approved budget figure exactly as it was recorded.
     */
    export interface ApprovedBudgetAmount {
        budgetLineId: string
        amount: MoneyAmount
        currency: CurrencyCode
        sourceKind: BudgetValueSourceKind
        recordedAt: string
        /**
         * Present only for `finance_system_import`.
         */
        sourceSystemKey?: string

        /**
         * Present only for `finance_system_import`.
         */
        sourceReference?: string
    }

    /**
     * Why a category is in the state it is in.
     * `NOTHING_RECORDED`       no approved budget and no actual. Nothing is known.
     * `AWAITING_ACTUAL`        an approved budget exists; no actual has been
     * entered. This is the state that must never render
     * as spend of zero.
     * `ACTUAL_WITHOUT_BUDGET`  an actual exists with no approved budget, so
     * remaining and percent used are undefined.
     * `BUDGET_AND_ACTUAL`      both are known and comparable.
     */
    export type BudgetPositionState = "NOTHING_RECORDED" | "AWAITING_ACTUAL" | "ACTUAL_WITHOUT_BUDGET" | "BUDGET_AND_ACTUAL"

    /**
     * The quantity one threshold rule judges a position by.
     * `percent_used`     the recorded actual as a percentage of the approved
     * budget. Undefined when the approved budget is zero,
     * because dividing by nothing has no answer.
     * `remaining_amount` the approved budget less the recorded actual, an exact
     * amount in the position's own currency. Defined even when
     * the approved budget is zero.
     * Both are known only once an approved budget and an actual both exist.
     */
    export type BudgetThresholdMeasure = "percent_used" | "remaining_amount"

    /**
     * How this position stands against the threshold policy governing its month.
     * `NOT_CONFIGURED` means the organisation has no approved threshold policy in
     * force for this month. It must never be presented as a reassuring green: it
     * means nobody had decided what good looked like for that month.
     * `GOVERNED` means a policy is in force, and `rules` carries what each of its
     * rules made of this position. There is deliberately no single overall band
     * here: with more than one approved rule, "the band" is a question with more
     * than one correct answer, and picking one would merge rules the approval
     * keeps separate.
     */
    export interface BudgetThresholdOutcome {
        state: "NOT_CONFIGURED" | "GOVERNED"
        /**
         * One entry per rule of the governing policy. Empty under `NOT_CONFIGURED`.
         */
        rules: BudgetThresholdRuleOutcome[]

        /**
         * The following are present only when `state` is `GOVERNED`.
         */
        policyKey?: string

        policyVersion?: number
        /**
         * The month from which the governing policy version took effect.
         */
        policyEffectiveFromMonth?: string
    }

    /**
     * What one governed threshold rule made of one position.
     * A policy carries one of these per rule, and they are resolved separately
     * against separate measures. Two rules may legitimately reach different
     * conclusions about the same position — a month can be inside its percentage
     * limit while almost nothing is left, and a month with no approved budget at
     * all can be judged on what remains but not on what percentage was used — so
     * neither is a summary of the other and neither may be dropped in favour of
     * the other.
     * `BANDED`         the rule's measure was known and one of its bands covers it.
     * `NOT_APPLICABLE` the rule could not judge this position; `reason` says why.
     * Absence is always `NOT_APPLICABLE`. A category with no actual recorded is
     * never banded, however wide the approved bands are, because there is no
     * measured value to fall into one.
     */
    export interface BudgetThresholdRuleOutcome {
        ruleCode: string
        ruleLabel: string
        measure: BudgetThresholdMeasure
        state: "BANDED" | "NOT_APPLICABLE"
        /**
         * Explains `NOT_APPLICABLE` rather than leaving the consumer to guess.
         */
        reason?: string

        /**
         * The following are present only when `state` is `BANDED`.
         */
        bandCode?: string

        bandLabel?: string
    }

    /**
     * Where a recorded financial value came from. `manual_entry` is what this
     * slice writes. `finance_system_import` exists so that a value posted by a
     * nominated finance system is distinguishable from a value someone typed,
     * without a schema or contract change when that integration is approved.
     */
    export type BudgetValueSourceKind = "manual_entry" | "finance_system_import"

    /**
     * One governed category's position for one centre-month.
     * Which fields are present is determined entirely by `state`:
     * | state                   | approvedBudget | actual | remaining | percentUsed |
     * | ----------------------- | -------------- | ------ | --------- | ----------- |
     * | `NOTHING_RECORDED`      | absent         | absent | absent    | absent      |
     * | `AWAITING_ACTUAL`       | present        | absent | absent    | absent      |
     * | `ACTUAL_WITHOUT_BUDGET` | absent         | present| absent    | absent      |
     * | `BUDGET_AND_ACTUAL`     | present        | present| present   | see below   |
     * The service builds these from an internal discriminated union
     * (`CentreBudgetPositionFacts` in `position.ts`), so a position carrying
     * `remaining` without an `actual` is not constructible.
     */
    export interface CentreBudgetCategoryPosition {
        categoryId: string
        categoryCode: string
        categoryName: string
        /**
         * A retired category still appears for a month that holds data against it,
         * so a historical month stays readable after the taxonomy moves on.
         */
        categoryStatus: "active" | "inactive"

        sortOrder: number
        state: BudgetPositionState
        approvedBudget?: ApprovedBudgetAmount
        actual?: RecordedActualAmount
        /**
         * Approved budget less recorded actual. Only ever present under `BUDGET_AND_ACTUAL`.
         */
        remaining?: MoneyAmount

        /**
         * Actual as a percentage of approved budget. Present under
         * `BUDGET_AND_ACTUAL` except when the approved budget is exactly zero:
         * dividing by nothing is undefined, not 0% and not 100%.
         */
        percentUsed?: PercentValue

        threshold: BudgetThresholdOutcome
    }

    export interface CentreBudgetMonthResponse {
        cacheControl: string
        asOf: string
        month: string
        centreId: string
        centreName: string
        status: "ready" | "partial"
        /**
         * One entry per governed category considered, including empty ones.
         */
        categories: CentreBudgetCategoryPosition[]

        summary: CentreBudgetMonthSummary
        /**
         * Whether the viewer may record an actual for this centre.
         */
        canEnterActual: boolean

        /**
         * True when no approved threshold policy governs this month, so no position
         * carries a band. Surfaces must say so rather than implying an all-clear.
         */
        thresholdPolicyConfigured: boolean

        warning?: string
    }

    /**
     * Roll-up across the categories of one centre-month.
     * Coverage governs which fields exist, on the same principle Centre Quality
     * uses. Counts of what is missing are known negative evidence and are always
     * safe to state. Sums are not: a total computed over a partly entered month
     * understates spend while looking authoritative, so every total is withheld
     * unless every contributing category is known and shares one currency.
     */
    export interface CentreBudgetMonthSummary {
        coverage: "complete" | "partial"
        /**
         * Governed categories considered for this centre-month.
         */
        categoryCount: number

        /**
         * Categories with an approved budget.
         */
        budgetedCategoryCount: number

        /**
         * Categories with a recorded actual, including deliberate zeros.
         */
        recordedActualCount: number

        /**
         * Categories with an approved budget and no actual yet. Known gap.
         */
        awaitingActualCount: number

        /**
         * Categories with an actual but no approved budget. Known gap.
         */
        actualWithoutBudgetCount: number

        /**
         * Categories with neither. Known gap.
         */
        nothingRecordedCount: number

        /**
         * The shared currency, present only when every recorded value agrees.
         */
        currency?: CurrencyCode

        /**
         * Present only when every category has an approved budget in one currency.
         */
        totalApprovedBudget?: MoneyAmount

        /**
         * The next three are present only under `complete` coverage.
         */
        totalRecordedActual?: MoneyAmount

        totalRemaining?: MoneyAmount
        totalPercentUsed?: PercentValue
        /**
         * Present only under `complete` coverage, where a month-level total may be
         * stated at all. Each governed rule judges the totals separately, so a rule
         * whose measure is undefined across the month says so rather than being
         * omitted.
         */
        threshold?: BudgetThresholdOutcome
    }

    /**
     * ISO-4217-shaped currency code, for example `"AUD"`.
     */
    export type CurrencyCode = string

    /**
     * An exact decimal amount rendered as a string, for example `"12345.67"` or
     * `"0.00"`.
     * It is deliberately not a `number`. PostgreSQL stores these as
     * `NUMERIC(14,2)`, and DATABASE_SCHEMA.md requires that "Monetary values use
     * fixed precision, explicit currency, financial period, and source date—not
     * floating point." A JSON number would be parsed into an IEEE-754 double by
     * every JavaScript client, which cannot represent every two-decimal value
     * exactly and would reintroduce the rounding error the database type exists to
     * prevent. Consumers must format or compare these with a decimal-aware
     * routine, never with `parseFloat`.
     */
    export type MoneyAmount = string

    /**
     * An exact percentage rendered as a string with two decimal places, for
     * example `"84.30"`. Same reasoning as `MoneyAmount`: it is computed in
     * PostgreSQL `NUMERIC` and never passes through a float.
     */
    export type PercentValue = string

    /**
     * `status` discriminates the response exactly as Centre Quality does.
     * `unsupported` means the viewer holds no budget read authority for any
     * centre. It queries no budget source, so it carries no `centres`, no
     * `coverage` and no counts. Returning an empty list with zero counts would
     * assert that the portfolio was checked and found empty, when nothing was
     * checked at all.
     */
    export interface PortfolioBudgetMonthResponse {
        cacheControl: string
        asOf: string
        month: string
        status: "ready" | "partial" | "unsupported"
        /**
         * The following are present only for an active projection.
         */
        centres?: PortfolioCentreBudgetCard[]

        /**
         * `partial` when a centre could not be authorised safely and was left out
         * entirely, or when any included centre's month is partly entered.
         */
        coverage?: "complete" | "partial"

        /**
         * Centres actually included above. Never an organisation total.
         */
        visibleCentreCount?: number

        /**
         * Included centres whose month is fully entered.
         */
        completeCentreCount?: number

        /**
         * Included centres still missing at least one actual. Known gap.
         */
        incompleteCentreCount?: number

        thresholdPolicyConfigured?: boolean
        warning?: string
    }

    export interface PortfolioCentreBudgetCard {
        centreId: string
        centreName: string
        summary: CentreBudgetMonthSummary
    }

    /**
     * Records or confirms one monthly actual. The amount is a decimal string for
     * the same reason it is returned as one; sending `0` and sending nothing must
     * not become the same request.
     */
    export interface RecordCentreBudgetActualRequest {
        categoryId: string
        /**
         * Exact decimal, up to two places, for example `"1250.00"`. `"0.00"` is a valid deliberate zero.
         */
        amount: MoneyAmount

        currency: CurrencyCode
        note?: string
        /**
         * Marks the entry as confirmed by the submitting Centre Director. Defaults
         * to false. Confirming an earlier figure resubmits it with `confirmed: true`,
         * which supersedes the previous record and preserves both states.
         */
        confirmed?: boolean
    }

    export interface RecordCentreBudgetActualResponse {
        cacheControl: string
        asOf: string
        month: string
        centreId: string
        /**
         * The resulting position for the category that was entered.
         */
        position: CentreBudgetCategoryPosition

        /**
         * The actual this entry superseded, when it corrected an earlier figure.
         */
        supersededActualId?: string
    }

    /**
     * A recorded actual exactly as it was entered. An `amount` of `"0.00"` here is
     * a real, deliberate zero: somebody stated that nothing was spent. The absence
     * of this whole object is what "not entered" looks like.
     */
    export interface RecordedActualAmount {
        actualId: string
        amount: MoneyAmount
        currency: CurrencyCode
        sourceKind: BudgetValueSourceKind
        enteredAt: string
        /**
         * Present only for `manual_entry`; the accountable person.
         */
        enteredByPrincipalId?: string

        /**
         * Present only for `finance_system_import`.
         */
        sourceSystemKey?: string

        /**
         * Present only for `finance_system_import`.
         */
        sourceReference?: string

        /**
         * The stated cutoff of the source data. Present only for
         * `finance_system_import`; a manual entry has no source cutoff and must not
         * be given a fabricated one.
         */
        sourceCutoffAt?: string

        note?: string
        /**
         * Whether the Centre Director who entered or reviewed this figure stands
         * behind it. This is a state on the record, not an approval workflow: there
         * is no approver capability, no pending state, and no second person
         * required. `false` is a known fact — the value is recorded but unconfirmed
         * — so it is a boolean rather than an omitted field.
         */
        confirmed: boolean

        /**
         * Present only when `confirmed` is true.
         */
        confirmedAt?: string

        /**
         * Present only when `confirmed` is true.
         */
        confirmedByPrincipalId?: string
    }
}

export namespace centre_quality {
    export interface CentreQualityCta {
        label: string
        route: string
    }

    /**
     * Each list is absent when its source did not report, and empty only when the
     * source was `AVAILABLE` and genuinely held no rows. `centre.coverage` states
     * which case applies, so the frontend never has to guess whether an empty
     * list means "none" or "not checked".
     */
    export interface CentreQualityDetailResponse {
        cacheControl: string
        asOf: string
        status: "ready" | "partial"
        centre: QualityCentreCard
        openActions?: QualityActionListItem[]
        completedActions?: QualityCompletedActionItem[]
        strengths?: QualityStrength[]
        uncoveredFindings?: QualityUncoveredFinding[]
        /**
         * Per-section standing for the latest finalised review. Empty when the
         * centre has no finalised review, rather than a fabricated zero row.
         */
        sectionResults?: QualitySectionResult[]

        reviewHistory?: QualityReviewSummary[]
        canAcknowledgeReview: boolean
        sourceHealth: QualitySourceHealth[]
        warning?: string
    }

    /**
     * Support grouping, deliberately not a rank or a score. It is derived only
     * from currently authorised source facts and is used to gather centres that
     * need the same kind of leadership response.
     * `INFORMATION_INCOMPLETE` is a statement about source coverage, not about a
     * centre's performance. It exists so that a missing source can never be
     * reported as the reassuring `STEADY` or `AWAITING_FIRST_REVIEW`.
     */
    export type CentreQualityFocus = "NEEDS_SUPPORT" | "MONITOR" | "INFORMATION_INCOMPLETE" | "STEADY" | "AWAITING_FIRST_REVIEW"

    export type CentreQualityTrend = "IMPROVED" | "STEADY" | "DECLINED" | "NOT_COMPARABLE"

    export interface CentreQualityView {
        kind: CentreQualityViewKind
        label: string
        centreId?: string
        centreName?: string
    }

    export type CentreQualityViewKind = "centre" | "portfolio" | "organisation"

    export interface CentreQualityWorkspaceRequest {
        view?: CentreQualityViewKind
        centreId?: string
    }

    /**
     * `status` discriminates the response, in the same way Daily Success does.
     * `ready` and `partial` are active projections and carry the business block:
     * `centres`, `focusGroups`, `summary`, `sourceHealth` and
     * `authorisationHealth`.
     * `selection_required` and `unsupported` query no business source at all, so
     * they carry none of that block. Returning `sourceHealth: AVAILABLE` or a
     * zero-filled summary in those states would assert that sources were checked
     * and found empty, when in fact nothing was checked. Only the authorisation
     * facts the request did establish — the authorised view choices and the
     * organisation timezone — are returned.
     */
    export interface CentreQualityWorkspaceResponse {
        cacheControl: string
        asOf: string
        status: "ready" | "partial" | "selection_required" | "unsupported"
        activeView?: CentreQualityView
        availableViews: CentreQualityView[]
        organisationTimezone: string
        /**
         * Present only for an active projection (`ready` or `partial`).
         */
        centres?: QualityCentreCard[]

        focusGroups?: QualityFocusGroup[]
        summary?: QualityPortfolioSummary
        sourceHealth?: QualitySourceHealth[]
        authorisationHealth?: QualityAuthorisationHealth
        warning?: string
    }

    export interface QualityActionListItem {
        correctiveActionId: string
        title: string
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
        status: string
        statusLabel: string
        responsibility: "YOU_NEED_TO_ACT" | "CENTRE_NEEDS_TO_ACT" | "WAITING_ON_SOMEONE_ELSE" | "FOR_YOUR_AWARENESS"
        dueAt: string
        dueLocalDate: string
        dueBucket: "OVERDUE" | "TODAY" | "TOMORROW" | "DUE_SOON" | "LATER"
        daysFromToday: number
        independentVerificationRequired: boolean
        cta: CentreQualityCta
    }

    /**
     * Counts of currently authorised, currently open corrective actions.
     */
    export interface QualityActionRollup {
        total: number
        critical: number
        overdue: number
        dueSoon: number
        awaitingVerification: number
        returned: number
        yourAction: number
        centreAction: number
        waiting: number
    }

    export interface QualityAuthorisationHealth {
        status: "available" | "partial"
        warning?: string
    }

    /**
     * Every count on this card is optional on purpose. A field is present only
     * when its source was `AVAILABLE`, so an unauthorised or failed source is
     * absent rather than zero. Consumers must render absence as "not checked",
     * never as "none".
     */
    export interface QualityCentreCard {
        centreId: string
        centreName: string
        timezone: string
        localDate: string
        coverage: QualityCentreCoverage
        focus: CentreQualityFocus
        focusReason: string
        /**
         * Present only when `coverage.quarterlyReviews` is `AVAILABLE`.
         */
        latestReview?: QualityReviewSummary

        comparison?: QualityQuarterComparison
        /**
         * Present only when `coverage.correctiveActions` is `AVAILABLE`.
         */
        actions?: QualityActionRollup

        /**
         * Present only when `coverage.uncoveredFindings` is `AVAILABLE`.
         */
        uncoveredCriticalFindings?: number

        strengthsCount?: number
        completedLast30Days?: number
        cta: CentreQualityCta
    }

    /**
     * Coverage is a per-centre fact because authorisation is evaluated per centre
     * per capability. One centre in a portfolio can have complete information
     * while another has none, and the two must not be summarised as if they were
     * the same.
     */
    export interface QualityCentreCoverage {
        /**
         * `quarterly_audit.read` plus the quarterly-review source query.
         */
        quarterlyReviews: QualitySourceCoverage

        /**
         * `corrective_action.read` plus the corrective-action source query.
         */
        correctiveActions: QualitySourceCoverage

        /**
         * `finding.read`, which gates uncovered critical findings separately.
         */
        uncoveredFindings: QualitySourceCoverage
    }

    export interface QualityCompletedActionItem {
        correctiveActionId: string
        title: string
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
        closedAt: string
        closedLocalDate: string
        cta: CentreQualityCta
    }

    export interface QualityFocusGroup {
        focus: CentreQualityFocus
        label: string
        description: string
        centreIds: string[]
    }

    /**
     * Coverage is `partial` when any centre's sources did not fully report, or
     * when a centre could not be authorised safely and was therefore left out of
     * the card set entirely. An omitted centre is invisible here by design, so
     * nothing below may be read as an organisation-complete statement unless
     * coverage is `complete`.
     * Known negative evidence stays visible under partial coverage: a centre that
     * is genuinely showing critical or overdue work is still counted. Every
     * reassuring count and every summed total is withheld instead, because those
     * are the values that would falsely imply an all-clear.
     */
    export interface QualityPortfolioSummary {
        coverage: "complete" | "partial"
        /**
         * Centres actually included below. Under `partial` coverage this is what
         * the viewer can see, never an organisation total.
         */
        visibleCentreCount: number

        /**
         * Known negative evidence: safe to state under either coverage.
         */
        needsSupportCount: number

        monitorCount: number
        informationIncompleteCount: number
        /**
         * Reassuring counts. Present only under `complete` coverage.
         */
        steadyCount?: number

        awaitingFirstReviewCount?: number
        /**
         * Summed totals. Present only when every contributing centre reported.
         */
        openCriticalCount?: number

        overdueCount?: number
        awaitingVerificationCount?: number
    }

    /**
     * Previous-quarter context. `available` is false when no earlier finalised
     * review exists; the frontend must then show an empty state rather than a
     * zero or a neutral trend.
     */
    export interface QualityQuarterComparison {
        available: boolean
        comparable: boolean
        trend: CentreQualityTrend
        previous?: QualityReviewSummary
        scoreDelta?: number
        criticalDelta?: number
        /**
         * Explains a `NOT_COMPARABLE` outcome instead of hiding it.
         */
        note?: string
    }

    /**
     * A finalised internal review exactly as the quarterly-review module stored it.
     */
    export interface QualityReviewSummary {
        auditRunId: string
        /**
         * Quarter-truncated review period start owned by `audit_runs`.
         */
        reviewPeriodStart: string

        /**
         * Formatted from `reviewPeriodStart`; never an invented schedule or due date.
         */
        quarterLabel: string

        finalisedAt: string
        templateVersionId: string
        overallScore?: number
        performanceBandLabel?: string
        riskStatus?: string
        coveragePercent?: number
        criticalFindingCount: number
        highFindingCount: number
        actionCount: number
        positivePracticeCount: number
        acknowledged: boolean
    }

    export interface QualitySectionResult {
        sectionId: string
        title: string
        /**
         * Presentation order owned by the audit template.
         */
        sortOrder: number

        standing: QualitySectionStanding
        /**
         * `audit_section_results.score`; absent when the section scored nothing.
         */
        score?: number

        /**
         * `audit_section_results.coverage_percent`, stated so a partly observed
         * section is never presented as a settled result.
         */
        coveragePercent: number

        /**
         * Movement against the same section last quarter, only when comparable.
         */
        previousScore?: number

        scoreDelta?: number
        trend: CentreQualityTrend
    }

    /**
     * How a section stands relative to the centre's own overall result for the
     * same review. This is a stated comparison between two numbers the
     * quarterly-review module already calculated, not a new score.
     * The values are deliberately relational. An earlier draft used `STRONG`,
     * which reads as an objective quality judgement and would have been applied
     * to a barely observed section purely because its number sat at or above the
     * centre's own overall result. Coverage is reported alongside so a partly
     * observed section is never mistaken for a settled one.
     */
    export type QualitySectionStanding = "BELOW_CENTRE_RESULT" | "AT_OR_ABOVE_CENTRE_RESULT" | "NOT_SCORED"

    /**
     * Whether a source domain actually contributed to this projection.
     * `AVAILABLE` means the source was queried successfully under the viewer's
     * current authorisation, so a zero result is a real zero. `NOT_AUTHORIZED`
     * and `UNAVAILABLE` both mean the projection does not know, and neither may
     * ever be presented as an absence of records.
     */
    export type QualitySourceCoverage = "AVAILABLE" | "NOT_AUTHORIZED" | "UNAVAILABLE"

    export interface QualitySourceHealth {
        source: "quarterly_reviews" | "corrective_actions"
        /**
         * Response-level roll-up of the per-centre coverage for this source.
         */
        status: QualitySourceCoverage
    }

    export interface QualityStrength {
        positiveObservationId: string
        description: string
        quarterLabel: string
    }

    export interface QualityUncoveredFinding {
        findingId: string
        headline: string
        severity: "CRITICAL"
        quarterLabel: string
    }
}

export namespace daily_success {
    export type DailyAttentionBand = "URGENT" | "TODAY" | "UPCOMING" | "WAITING" | "AWARENESS"

    export interface DailyAuthorisationHealth {
        status: "available" | "partial"
        warning?: string
    }

    export interface DailyBusinessDateContext {
        scope: "organisation" | "centre"
        id: string
        timezone: string
        date: string
    }

    export interface DailyCentreAttentionSummary {
        centreId: string
        centreName: string
        attentionBand: DailyAttentionBand
        headline: string
        coverage: "complete" | "partial"
        criticalCount?: number
        overdueCount?: number
        dueTodayCount?: number
        totalActiveCount?: number
        cta: DailySuccessCta
    }

    export type DailyDueBucket = "OVERDUE" | "TODAY" | "TOMORROW" | "DUE_SOON" | "LATER"

    export interface DailyDueInformation {
        at: string
        timezone: string
        localDate: string
        bucket: DailyDueBucket
        daysFromToday: number
    }

    export interface DailyPositiveContext {
        completedTodayCount: number
        recentTitles: string[]
        onTrackCentreCount?: number
    }

    export type DailyResponsibility = "YOU_NEED_TO_ACT" | "YOUR_CENTRE_NEEDS_TO_ACT" | "WAITING_ON_SOMEONE_ELSE" | "FOR_YOUR_AWARENESS"

    export interface DailySourceHealth {
        source: "corrective_actions" | "quarterly_reviews" | "people_access"
        status: "available" | "unavailable" | "not_applicable"
    }

    export interface DailySuccessCta {
        label: string
        route: string
    }

    export interface DailySuccessItem {
        id: string
        sourceType: "corrective_action" | "finding" | "quarterly_review" | "people_access"
        sourceId: string
        centreId?: string
        centreName?: string
        headline: string
        summary: string
        attentionBand: DailyAttentionBand
        responsibility: DailyResponsibility
        whyShown: DailyWhyShown
        due?: DailyDueInformation
        riskLevel: "CRITICAL" | "HIGH" | "STANDARD"
        verification?: {
            required: true
            eligible: boolean
        }
        cta: DailySuccessCta
    }

    export interface DailySuccessPerspective {
        kind: DailySuccessPerspectiveKind
        label: string
        centreId?: string
        centreName?: string
    }

    export type DailySuccessPerspectiveKind = "centre" | "portfolio" | "compliance" | "administration"

    export interface DailySuccessRequest {
        perspective?: DailySuccessPerspectiveKind
        centreId?: string
    }

    export interface DailySuccessResponse {
        cacheControl: string
        asOf: string
        status: "ready" | "partial" | "selection_required" | "unsupported"
        activePerspective?: DailySuccessPerspective
        availablePerspectives: DailySuccessPerspective[]
        businessDates: DailyBusinessDateContext[]
        sections: DailySuccessSection[]
        attentionCentres: DailyCentreAttentionSummary[]
        verificationItems: DailySuccessItem[]
        aggregateCounts: {
            coverage: "complete" | "partial"
            active?: number
            urgent?: number
            dueToday?: number
            waiting?: number
            distinctCentres?: number
        }
        positiveContext?: DailyPositiveContext
        sourceHealth: DailySourceHealth[]
        authorisationHealth: DailyAuthorisationHealth
        warning?: string
        workspaceLinks: DailyWorkspaceLink[]
    }

    export interface DailySuccessSection {
        key: "DO_FIRST" | "TODAY" | "NEXT" | "WAITING" | "ON_TRACK"
        label: "DO FIRST" | "TODAY" | "NEXT" | "WAITING" | "ON TRACK"
        items: DailySuccessItem[]
    }

    export interface DailyWhyShown {
        code: "CRITICAL_RISK" | "IMMEDIATE_RISK" | "ACTION_OVERDUE" | "ACTION_DUE_TODAY" | "ACTION_DUE_SOON" | "REMEDIATION_RETURNED" | "REMEDIATION_REQUIRED" | "VERIFICATION_REQUIRED" | "AUDIT_REQUIRES_ACTION" | "REVIEW_REQUIRES_ACKNOWLEDGEMENT" | "PRIVILEGED_APPROVAL_REQUIRED" | "IDENTITY_REVIEW_REQUIRED"
        label: string
    }

    export interface DailyWorkspaceLink {
        label: string
        route: string
    }
}

export namespace navigation {
    export interface NavigationResponse {
        cacheControl: string
        links: WorkspaceLink[]
    }

    export interface WorkspaceLink {
        label: string
        route: string
    }
}

export namespace people_access {
    export interface AcceptInvitationRequest {
        invitationToken: string
    }

    export interface AcceptInvitationResponse {
        outcome: "activated" | "awaiting_approval" | "administrator_review"
        invitationStatus: InvitationStatus
    }

    export interface AccessHistoryResponse {
        events: {
            id: string
            action: string
            resourceType: string
            occurredAt: string
            actorDisplayName: string | null
            reasonRecorded: boolean
        }[]
    }

    export interface AddAssignmentRequest {
        assignment: ProposedAssignment
        reason: string
        principalLockVersion: number
    }

    export interface AssignmentMutationRequest {
        reason: string
        principalLockVersion: number
        replacementScopes?: ProposedScope[]
    }

    export interface AssignmentMutationRequest {
        reason: string
        principalLockVersion: number
        replacementScopes?: ProposedScope[]
    }

    export interface CreateInvitationRequest {
        email: string
        displayName: string
        assignments: ProposedAssignment[]
        reason: string
    }

    export type InvitationScopeSummary = {
        scopeType: "organisation"
        displayName: string
    } | {
        scopeType: "organisational_unit"
        organisationalUnitId: string
        displayName: string
    } | {
        scopeType: "centre"
        centreId: string
        displayName: string
    }

    export type InvitationStatus = "DRAFT" | "SENT" | "IDENTITY_VERIFIED" | "AWAITING_PRIVILEGED_APPROVAL" | "ADMINISTRATOR_REVIEW" | "ACTIVATED" | "CANCELLED" | "EXPIRED"

    export interface InvitationSummary {
        id: string
        organisationName: string
        intendedEmail: string
        displayName: string
        status: InvitationStatus
        privilegeClass: PrivilegeClass
        packageVersion: number
        requestedByName: string
        requestReason: string
        expiresAt: string | null
        lockVersion: number
        assignments: {
            roleKey: string
            roleName: string
            roleVersion: number
            privilegeClass: PrivilegeClass
            effectiveFrom: string
            effectiveTo: string | null
            scopes: InvitationScopeSummary[]
        }[]
    }

    export interface PeopleAccessOptionsResponse {
        roles: {
            roleKey: string
            name: string
            scopeMode: "multi_centre" | "single_centre" | "organisation" | "flexible"
            approval: "standard" | "privileged" | "review"
        }[]
        centres: {
            id: string
            name: string
        }[]
        organisationalUnits: {
            id: string
            name: string
            kind: string
        }[]
    }

    export interface PeopleListResponse {
        people: PersonSummary[]
        invitations: InvitationSummary[]
    }

    export interface PersonAccessResponse {
        person: PersonSummary
    }

    export interface PersonSummary {
        principalId: string
        displayName: string
        status: PrincipalLifecycleStatus
        microsoftIdentity: "connected" | "not_connected"
        assignments: {
            id: string
            roleKey: string
            roleName: string
            scopes: ProposedScope[]
        }[]
        lockVersion: number
    }

    export interface PrincipalLifecycleRequest {
        reason: string
        lockVersion: number
    }

    export interface PrincipalLifecycleRequest {
        reason: string
        lockVersion: number
    }

    export interface PrincipalLifecycleRequest {
        reason: string
        lockVersion: number
    }

    export interface PrincipalLifecycleResponse {
        principalId: string
        status: PrincipalLifecycleStatus
        lockVersion: number
    }

    export type PrincipalLifecycleStatus = "pending" | "active" | "suspended" | "revoked"

    export type PrivilegeClass = "STANDARD" | "PRIVILEGED" | "REVIEW"

    export interface ProposedAssignment {
        roleKey: string
        scopes: ProposedScope[]
        effectiveFrom?: string
        effectiveTo?: string
    }

    export type ProposedScope = {
        scopeType: "organisation"
    } | {
        scopeType: "organisational_unit"
        organisationalUnitId: string
    } | {
        scopeType: "centre"
        centreId: string
    }

    export interface VersionedInvitationRequest {
        lockVersion: number
        reason?: string
    }

    export interface VersionedInvitationRequest {
        lockVersion: number
        reason?: string
    }

    export interface VersionedInvitationRequest {
        lockVersion: number
        reason?: string
    }

    export interface VersionedInvitationRequest {
        lockVersion: number
        reason?: string
    }
}

export namespace quarterly_reviews {
    export interface AcknowledgeAuditRequest {
        comment?: string
    }

    export interface AcknowledgeAuditResponse {
        acknowledgementId: string
        acknowledgedAt: string
    }

    export interface ActionTransitionResponse {
        actionId: string
        status: CorrectiveActionStatus
        lockVersion: number
    }

    export interface AuditCentreSummary {
        id: string
        name: string
        previousAuditDate?: string
        previousScore?: number
        openCorrectiveActions: number
    }

    export interface AuditItemView {
        id: string
        lineageKey: string
        wording: string
        instructions?: string
        weight: number
        scored: boolean
        critical: boolean
        evidenceRequirement: "none" | "optional" | "required"
        allowedOutcomes: AuditOutcome[]
        response?: {
            id: string
            outcome: AuditOutcome
            comment?: string
            locationContext?: string
            selectedOwnerPrincipalId?: string
            lockVersion: number
        }
        finding?: {
            id: string
            severity: FindingSeverity
            status: FindingStatus
            repeatCount: number
            actionId?: string
        }
    }

    export type AuditOutcome = "COMPLIANT" | "PARTIALLY_COMPLIANT" | "NON_COMPLIANT" | "NOT_APPLICABLE" | "NOT_OBSERVED" | "IMMEDIATE_ACTION_REQUIRED" | "POSITIVE_PRACTICE"

    export interface AuditOwnerCandidate {
        principalId: string
        displayName: string
    }

    export interface AuditPreparationResponse {
        centre: {
            id: string
            name: string
        }
        activeTemplate: {
            id: string
            title: string
            version: number
            synthetic: boolean
        }
        previousAudit?: {
            id: string
            finalisedAt: string
            score?: number
        }
        openCorrectiveActions: number
    }

    export type AuditRiskStatus = "STRONG" | "IMPROVEMENT_REQUIRED" | "AT_RISK" | "PRIORITY_INTERVENTION" | "HIGH" | "CRITICAL"

    export interface AuditSectionView {
        id: string
        title: string
        instructions?: string
        items: AuditItemView[]
        score?: number
    }

    export type AuditStatus = "DRAFT" | "IN_PROGRESS" | "READY_FOR_REVIEW" | "FINALISED"

    export interface AuditStatusTransitionResponse {
        status: AuditStatus
        lockVersion: number
    }

    export interface AuditTransitionRequest {
        lockVersion: number
    }

    export interface AuditTransitionRequest {
        lockVersion: number
    }

    export interface CompleteEvidenceUploadResponse {
        evidenceId: string
        scanStatus: "not_scanned" | "clean" | "rejected"
        availabilityStatus: string
        warning?: string
    }

    export interface ComplianceOversightResponse {
        counts: {
            completed: number
            inProgress: number
            outstanding: number
            centresBelowInternalThreshold: number
            criticalFindings: number
            highFindings: number
            openCorrectiveActions: number
            overdueCorrectiveActions: number
            awaitingVerification: number
        }
        centres: {
            centreId: string
            centreName: string
            latestAuditId?: string
            latestScore?: number
            riskStatus?: AuditRiskStatus
            openActions: number
            overdueActions: number
        }[]
    }

    export interface CorrectiveActionDetail {
        finding: {
            id: string
            description: string
            originatingAuditId: string
            originatingAuditStatus: AuditStatus
            originatingAuditAcknowledged: boolean
            itemLineageKey: string
            repeatCount: number
        }
        requiredRemediation: string
        evidenceRequirement: "none" | "optional" | "required"
        lockVersion: number
        evidence: {
            id: string
            filename: string
            mediaType: string
            byteSize?: number
            scanStatus: "not_scanned" | "clean" | "rejected"
            availabilityStatus: string
        }[]
        history: {
            eventType: string
            fromStatus?: string
            toStatus: string
            reason?: string
            occurredAt: string
        }[]
        id: string
        centreId: string
        centreName: string
        title: string
        severity: FindingSeverity
        dueAt: string
        status: CorrectiveActionStatus
        ownerPrincipalId?: string
        verificationRequired: boolean
        submittedAt?: string
    }

    export type CorrectiveActionStatus = "OPEN" | "IN_PROGRESS" | "VERIFICATION_REQUIRED" | "CLOSED" | "MORE_INFORMATION_REQUIRED" | "REJECTED" | "WITHDRAWN"

    export interface CorrectiveActionSummary {
        id: string
        centreId: string
        centreName: string
        title: string
        severity: FindingSeverity
        dueAt: string
        status: CorrectiveActionStatus
        ownerPrincipalId?: string
        verificationRequired: boolean
        submittedAt?: string
    }

    export interface FinaliseQuarterlyAuditResponse {
        auditId: string
        status: "FINALISED"
        score: number | null
        riskStatus: AuditRiskStatus
    }

    export type FindingSeverity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"

    export type FindingStatus = "OPEN" | "RESOLVED" | "WITHDRAWN"

    export interface GetEvidenceAccessResponse {
        downloadUrl: string
        expiresInSeconds: number
        scanStatus: "not_scanned" | "clean"
        warning?: string
    }

    export interface ListAuditCentresResponse {
        centres: AuditCentreSummary[]
    }

    export interface ListCorrectiveActionsResponse {
        actions: CorrectiveActionSummary[]
    }

    export interface QuarterlyAuditView {
        id: string
        centre: {
            id: string
            name: string
        }
        template: {
            id: string
            title: string
            version: number
            synthetic: boolean
            sourceClassification: string
        }
        status: AuditStatus
        reviewPeriodStart: string
        lockVersion: number
        progress: {
            answered: number
            total: number
        }
        score?: number
        coveragePercent?: number
        riskStatus?: AuditRiskStatus
        performanceBand?: {
            code: string
            label: string
        }
        previousComparison?: {
            auditId: string
            score?: number
            difference?: number
        }
        ownerCandidates: AuditOwnerCandidate[]
        sections: AuditSectionView[]
        positivePractices: {
            id: string
            description: string
        }[]
        acknowledged: boolean
    }

    export interface RequestEvidenceUploadRequest {
        targetType: "AUDIT_RESPONSE" | "CORRECTIVE_ACTION"
        targetId: string
        filename: string
        mediaType: "image/jpeg" | "image/png" | "application/pdf"
    }

    export interface RequestEvidenceUploadResponse {
        evidenceId: string
        uploadUrl: string
        expiresInSeconds: number
    }

    export interface ReturnCorrectiveActionRequest {
        lockVersion: number
        reason: string
        disposition?: "MORE_INFORMATION_REQUIRED" | "REJECTED"
    }

    export interface SaveAuditResponseRequest {
        outcome: AuditOutcome
        comment?: string
        locationContext?: string
        selectedOwnerPrincipalId?: string
        responseLockVersion?: number
        responseCorrectionReason?: string
    }

    export interface SaveAuditResponseResponse {
        responseId: string
        lockVersion: number
        auditStatus: AuditStatus
        immediateFindingCreated: boolean
        immediateActionCreated: boolean
        ownerResolutionRequired: boolean
    }

    export interface StartCorrectiveActionRequest {
        lockVersion: number
    }

    export interface StartQuarterlyAuditRequest {
        centreId: string
    }

    export interface StartQuarterlyAuditResponse {
        auditId: string
        status: AuditStatus
        created: boolean
    }

    export interface SubmitCorrectiveActionRequest {
        lockVersion: number
        remediationNote: string
    }

    export interface VerifyCorrectiveActionRequest {
        lockVersion: number
        verificationNote?: string
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}


// mustBeSet will throw an APIError with the Data Loss code if value is null or undefined
function mustBeSet<A>(field: string, value: A | null | undefined): A {
    if (value === null || value === undefined) {
        throw new APIError(
            500,
            {
                code: ErrCode.DataLoss,
                message: `${field} was unexpectedly ${value}`, // ${value} will create the string "null" or "undefined"
            },
        )
    }
    return value
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | authentication.AuthenticationParams
  | Promise<authentication.AuthenticationParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "bright-steps-centre-success-uwhi-Generated-TS-Client (Encore/v1.57.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: authentication.AuthenticationParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
